# Generated by Django 5.0.4 on 2024-05-13 06:50

import datetime
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sessions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField()),
                ("title", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=250)),
                ("instructions", models.TextField(default="")),
                (
                    "time_to_answer_question",
                    models.DurationField(default=datetime.timedelta(seconds=5)),
                ),
                (
                    "time_between_questions",
                    models.DurationField(default=datetime.timedelta(seconds=3)),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.game"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="game",
            name="current_instance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_instance",
                to="game.gameinstance",
            ),
        ),
        migrations.CreateModel(
            name="GameInstanceQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.gameinstance",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gameinstance",
            name="current_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="game.gameinstancequestion",
            ),
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sessions.session",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer",
                    django.contrib.gis.db.models.fields.GeometryField(srid=4326),
                ),
                ("score", models.IntegerField()),
                ("distance_km", models.FloatField()),
                (
                    "game_instance_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.gameinstancequestion",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.player"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=250)),
                (
                    "image",
                    models.FileField(
                        blank=True, null=True, upload_to="question/image/"
                    ),
                ),
                (
                    "answer",
                    django.contrib.gis.db.models.fields.GeometryField(srid=4326),
                ),
                (
                    "answer_label",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.game"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gameinstancequestion",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="game.question"
            ),
        ),
        migrations.AddIndex(
            model_name="gameinstancequestion",
            index=models.Index(
                fields=["asked_at"], name="game_gamein_asked_a_2e4fb7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gameinstancequestion",
            unique_together={("game_instance", "question")},
        ),
    ]
