---
# Install system apt packages
- hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: 'yes'
      update_cache: 'yes'
      cache_valid_time: 86400  # One day
  - name: Install packages
    apt: 
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - python3-pip
      - python3-dev
      - python3-venv
      - nginx
  - name: Install virtualenv via pip
    pip:
      name: virtualenv
      executable: pip3

# Install the app
- hosts: all
  tasks:
  - name: Clone repo
    git:
      repo: 'https://github.com/abrenaut/posio.git'
      dest: /home/{{ ansible_ssh_user }}/posio
      update: yes  # Does a git pull if the repo already exists  
  - name: Install requirements in a virtualenv
    pip:
      requirements: /home/{{ ansible_ssh_user }}/posio/requirements.txt
      virtualenv: /home/{{ ansible_ssh_user }}/virtualenvs/posio
      virtualenv_python: python3

# Configure app systemd service and nginx
- hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: Template systemd service config
    template:
      src: service.tpl
      dest: /etc/systemd/system/posio.service
  - name: Start systemd app service
    systemd:
      name: posio.service
      state: restarted
      enabled: yes
      daemon_reload: yes
  - name: Template nginx site config
    template:
      src: nginx.tpl
      dest: /etc/nginx/sites-available/posio
  - name: Enable nginx site
    file:
      src: /etc/nginx/sites-available/posio
      dest: /etc/nginx/sites-enabled/default
      state: link
      force: yes
  - name: Restart nginx
    systemd: name=nginx state=restarted enabled=yes
  - name: Open firewall for nginx
    ufw:
      rule: allow
      name: Nginx Full

